version: "3.9"
services:
  actix-forum:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/actix-forum/
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
